###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - 'https://github.com/Wuemeli/visualpay:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=Password12345%
            - MYSQL_DATABASE=visualpay
            - MYSQL_USER=visualpay
            - MYSQL_PASSWORD=Password12345%
        ports:
            - '8002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - 'https://github.com/Wuemeli/visualpay:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - 'https://github.com/Wuemeli/visualpay:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
